### ISSUE TITLE
Feature release branch

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client-test-node#13]
Proposal: new branch with the same name as the substrate-branch its pointing to.

**Comment by brenzi** [comment]
can you please add reasoning for this?

**Comment by haerdib** [comment]
Ah sorry. This issue is related to the incoming update to substrate v4.0.0-dev and https://github.com/scs/substrate-api-client/issues/141. So substrate-api-client (and this test node) will have a branch pointing to substrate 3.0.0 for api-client users that do not yet want to update to 4.0.0-dev
